### ISSUE TITLE
Client-side Q&A display

### ISSUE THREAD

**Issue by BlayTheNinth** [BetterThanMinecon/ConventionCraft#4]
Chat isn't really clean (op commands, joins/parts) and doesn't look good on recording, so there should be a client-side display for messages that start with [Q] (and [A] for written answers)

Edit: (shadowfacts) Fix Blay's Markdown

**Comment by shadowfacts** [comment]
Your welcome :P

**Comment by blay09** [comment]
Did you suggest that too or what? :P

**Comment by shadowfacts** [comment]
Look at the end of your first comment :P
